using DubbingPlatform.Application.Configuration;
using DubbingPlatform.Application.Errors;
using DubbingPlatform.Application.Exceptions;
using DubbingPlatform.Application.MultiTenancy;
using DubbingPlatform.Application.Options;
using DubbingPlatform.Application.Orchestration;
using DubbingPlatform.Application.Providers;
using DubbingPlatform.Application.StateMachines;
using DubbingPlatform.Domain.Entities;
using DubbingPlatform.Domain.Enums;
using DubbingPlatform.Domain.Exceptions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace DubbingPlatform.Application.Services;

/// <summary>
/// Result of a processing start: the new run identity plus the hashes needed
/// for the <c>RunStarted</c> publish.
/// </summary>
public sealed record ProcessingStartResult(
    Guid RunId,
    int Attempt,
    string PipelineVersion,
    string ConfigurationHash,
    string ProviderRouteHash,
    string ExecutionSnapshotHash,
    DateTimeOffset CreatedAt,
    DateTimeOffset? StartedAt,
    string Status);

/// <summary>
/// Explicit processing-start workflow. Validates the project is
/// <c>MediaReady</c> (else 409 <c>CONFLICT</c>), rejects a second start while
/// an active run exists (partial-unique statuses
/// Pending/Running/Cancelling/ManualReviewRequired, else 409; concurrent
/// starters serialize on the <c>processing_runs_project_id</c> partial-unique
/// index and the loser observes 409), enforces the tenant active-run quota
/// (<c>Quota:MaxActiveProjects</c>, else 429 <c>QUOTA_EXCEEDED</c>) and the
/// tenant privacy policy (<see cref="PolicyChecker"/>, else 403
/// <c>POLICY_DENIED</c>), then atomically inserts the <c>ProcessingRun</c>
/// (Attempt = max+1, PipelineVersion <c>1.0.0</c>, deterministic hashes), the
/// <c>ProviderRouteSnapshot</c> row, one <c>RunStageSummary</c> per DAG stage
/// (Project/Run scope <c>ExpectedUnits=1</c>, Segment/Speaker/Window
/// <c>0</c> for the dispatcher to set later via
/// <see cref="BarrierService.EnsureSummaryAsync"/>) and transitions the
/// project MediaReady→Processing with <c>ActiveRunId</c>.
/// Cost preflight uses the frozen <c>ICostGate.CanProceedAsync</c> contract
/// (allow-all until Task 036; there is no <c>EstimateAsync</c> on that
/// contract) and runs in the controller before this service so Application
/// never references Infrastructure.
/// </summary>
public sealed class ProcessingStartService
{
    /// <summary>
    /// Frozen pipeline version for every run created here.
    /// </summary>
    public const string PipelineVersion = "1.0.0";

    private static readonly ProcessingRunStatus[] ActiveStatuses =
    [
        ProcessingRunStatus.Pending,
        ProcessingRunStatus.Running,
        ProcessingRunStatus.Cancelling,
        ProcessingRunStatus.ManualReviewRequired,
    ];

    private readonly IStageExecutionContextFactory _contextFactory;
    private readonly QuotaOptions _quota;
    private readonly ILogger<ProcessingStartService> _logger;

    public ProcessingStartService(
        IStageExecutionContextFactory contextFactory,
        IOptions<QuotaOptions> quotaOptions,
        ILogger<ProcessingStartService> logger)
    {
        ArgumentNullException.ThrowIfNull(contextFactory);
        ArgumentNullException.ThrowIfNull(quotaOptions);
        ArgumentNullException.ThrowIfNull(logger);
        _contextFactory = contextFactory;
        _quota = quotaOptions.Value;
        _logger = logger;
    }

    /// <summary>
    /// Starts a run for <paramref name="projectId"/> using the pre-generated
    /// <paramref name="runId"/> (generated by the caller so the cost preflight
    /// can reference it before any write).
    /// </summary>
    public async Task<ProcessingStartResult> StartAsync(
        Guid tenantId,
        Guid projectId,
        string actor,
        Guid runId,
        CancellationToken cancellationToken = default)
    {
        RequireTenant(tenantId);
        RequireId(projectId, nameof(projectId));
        RequireId(runId, nameof(runId));
        ArgumentException.ThrowIfNullOrWhiteSpace(actor);

        var project = await LoadOwnedProjectAsync(tenantId, projectId, cancellationToken).ConfigureAwait(false);
        if (project.Status != ProjectStatus.MediaReady)
        {
            throw new ConflictException(
                $"Project '{projectId}' is '{project.Status}'; media must be validated (MediaReady) before starting processing.");
        }

        var asset = await LoadValidAssetAsync(tenantId, projectId, cancellationToken).ConfigureAwait(false);
        if (asset is null)
        {
            throw new ConflictException(
                $"Project '{projectId}' has no validated media; upload and validate media before starting processing.");
        }

        await EnsureNoActiveRunAsync(tenantId, projectId, cancellationToken).ConfigureAwait(false);
        await EnsureQuotaAsync(tenantId, cancellationToken).ConfigureAwait(false);
        var policy = await LoadPolicyAsync(tenantId, cancellationToken).ConfigureAwait(false);
        EnsurePrivacy(policy);

        var now = DateTimeOffset.UtcNow;
        var attempt = await NextAttemptAsync(tenantId, projectId, cancellationToken).ConfigureAwait(false);
        var configurationHash = project.ConfigurationHash;
        var snapshot = ProviderRouteSnapshotBuilder.Build(
            tenantId,
            projectId,
            runId,
            new { pipelineVersion = PipelineVersion, sourceLanguage = project.SourceLanguage, targetLanguage = project.TargetLanguage },
            new { providers = new[] { "mock" } },
            new
            {
                externalProvidersAllowed = policy?.ExternalProvidersAllowed ?? false,
                allowedProviders = policy?.AllowedProviders ?? [],
                residencyConstraint = policy?.ResidencyConstraint,
            });
        var providerRouteHash = snapshot.RouteConfigHash;
        var policyHash = ConfigurationHashCalculator.Compute(new
        {
            externalProvidersAllowed = policy?.ExternalProvidersAllowed ?? false,
            allowedProviders = policy?.AllowedProviders ?? Array.Empty<string>(),
            residencyConstraint = policy?.ResidencyConstraint ?? string.Empty,
            sensitivePolicy = policy?.SensitivePolicy ?? string.Empty,
            voicePolicy = policy?.VoicePolicy ?? string.Empty,
        });
        var executionSnapshotHash = ExecutionSnapshotCalculator.Compute(
            new { pipelineVersion = PipelineVersion, configurationHash },
            providerRouteHash,
            [asset.ContentHash],
            [],
            policyHash);

        var run = new ProcessingRun(
            runId, tenantId, projectId, attempt, ProcessingRunStatus.Pending,
            PipelineVersion, configurationHash, providerRouteHash, executionSnapshotHash,
            now, now, null, null);

        using (TenantContext.BeginScope(tenantId))
        {
            using var db = _contextFactory.CreateDbContext();
            using var transaction = await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                db.Set<ProcessingRun>().Add(run);
                db.Set<ProviderRouteSnapshot>().Add(snapshot);
                foreach (var node in StageGraph.Nodes)
                {
                    var expected = node.Scope is ScopeType.Project or ScopeType.Run ? 1 : 0;
                    db.Set<RunStageSummary>().Add(new RunStageSummary(
                        Guid.NewGuid(), tenantId, runId, node.StageType, expected,
                        0, 0, 0, 0, 0, now, now));
                }

                await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

                ProjectStateMachine.EnsureCanTransition(ProjectStatus.MediaReady, ProjectStatus.Processing);
                await db.Database.ExecuteSqlRawAsync(
                    "UPDATE dubbing_projects SET status = {0}, active_run_id = {1}, updated_at = {2} WHERE id = {3} AND tenant_id = {4}",
                    ProjectStatus.Processing.ToString(), runId, now, projectId, tenantId).ConfigureAwait(false);

                await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsUniqueViolation(ex))
            {
                try
                {
                    await db.Database.RollbackTransactionAsync(cancellationToken).ConfigureAwait(false);
                }
                catch (Exception)
                {
                    // Rollback best effort; original conflict propagates.
                }

                throw new ConflictException(
                    $"Project '{projectId}' already has an active processing run; cancel it before starting a new one.", ex);
            }
            catch
            {
                try
                {
                    await db.Database.RollbackTransactionAsync(cancellationToken).ConfigureAwait(false);
                }
                catch (Exception)
                {
                }

                throw;
            }
        }

        _logger.LogInformation(
            "Started processing run {RunId} for project {ProjectId} (attempt {Attempt}, pipeline {Pipeline}).",
            runId, projectId, attempt, PipelineVersion);

        return new ProcessingStartResult(
            runId, attempt, PipelineVersion, configurationHash,
            providerRouteHash, executionSnapshotHash, now, null, ProcessingRunStatus.Pending.ToString());
    }

    private async Task<DubbingProject> LoadOwnedProjectAsync(Guid tenantId, Guid projectId, CancellationToken cancellationToken)
    {
        DubbingProject? project;
        bool isDeleted;
        using (TenantContext.BeginMaintenanceScope())
        {
            using var db = _contextFactory.CreateDbContext();
            project = await db.Set<DubbingProject>()
                .AsNoTracking()
                .FirstOrDefaultAsync(p => p.Id == projectId, cancellationToken).ConfigureAwait(false);
            if (project is null)
            {
                throw new NotFoundException($"Project '{projectId}' was not found.");
            }

            isDeleted = await db.Set<DubbingProject>()
                .Where(p => p.Id == projectId)
                .Select(p => EF.Property<bool>(p, "IsDeleted"))
                .FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
        }

        if (project.TenantId != tenantId)
        {
            throw new ForbiddenException($"Project '{projectId}' does not belong to the current tenant.");
        }

        if (isDeleted)
        {
            throw new NotFoundException($"Project '{projectId}' was not found.");
        }

        return project;
    }

    private async Task<MediaAsset?> LoadValidAssetAsync(Guid tenantId, Guid projectId, CancellationToken cancellationToken)
    {
        using (TenantContext.BeginScope(tenantId))
        {
            using var db = _contextFactory.CreateDbContext();
            return await db.Set<MediaAsset>()
                .AsNoTracking()
                .Where(a => a.ProjectId == projectId && a.Status == MediaAssetStatus.Valid)
                .OrderBy(a => a.CreatedAt)
                .FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
        }
    }

    private async Task EnsureNoActiveRunAsync(Guid tenantId, Guid projectId, CancellationToken cancellationToken)
    {
        using (TenantContext.BeginScope(tenantId))
        {
            using var db = _contextFactory.CreateDbContext();
            var active = await db.Set<ProcessingRun>()
                .AsNoTracking()
                .Where(r => r.ProjectId == projectId && ActiveStatuses.Contains(r.Status))
                .OrderByDescending(r => r.CreatedAt)
                .FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
            if (active is not null)
            {
                throw new ConflictException(
                    $"Project '{projectId}' already has an active run '{active.Id}' ({active.Status}).");
            }
        }
    }

    private async Task EnsureQuotaAsync(Guid tenantId, CancellationToken cancellationToken)
    {
        using (TenantContext.BeginScope(tenantId))
        {
            using var db = _contextFactory.CreateDbContext();
            var activeCount = await db.Set<ProcessingRun>()
                .Where(r => ActiveStatuses.Contains(r.Status))
                .CountAsync(cancellationToken).ConfigureAwait(false);
            if (activeCount >= _quota.MaxActiveProjects)
            {
                throw new QuotaExceededException(
                    $"Tenant has {activeCount} active processing runs (max {_quota.MaxActiveProjects}).");
            }
        }
    }

    private async Task<ProcessingPolicy?> LoadPolicyAsync(Guid tenantId, CancellationToken cancellationToken)
    {
        using (TenantContext.BeginScope(tenantId))
        {
            using var db = _contextFactory.CreateDbContext();
            return await db.Set<ProcessingPolicy>()
                .AsNoTracking()
                .Where(p => p.TenantId == tenantId)
                .OrderBy(p => p.CreatedAt)
                .FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
        }
    }

    private static void EnsurePrivacy(ProcessingPolicy? policy)
    {
        if (policy is null)
        {
            return;
        }

        if (!PolicyChecker.CanUseProvider(policy, ProviderType.Mock, null))
        {
            throw new ErrorCodeException(
                ErrorCodes.PolicyDenied,
                "Tenant policy denies processing for this project.");
        }
    }

    private async Task<int> NextAttemptAsync(Guid tenantId, Guid projectId, CancellationToken cancellationToken)
    {
        using (TenantContext.BeginScope(tenantId))
        {
            using var db = _contextFactory.CreateDbContext();
            var max = await db.Set<ProcessingRun>()
                .Where(r => r.ProjectId == projectId)
                .MaxAsync(r => (int?)r.Attempt, cancellationToken).ConfigureAwait(false);
            return (max ?? -1) + 1;
        }
    }

    private static bool IsUniqueViolation(Exception exception)
    {
        for (var current = exception; current is not null; current = current.InnerException)
        {
            if (current is DbUpdateException)
            {
                return true;
            }
        }

        return false;
    }

    private static void RequireTenant(Guid tenantId)
    {
        if (tenantId == Guid.Empty)
        {
            throw new DomainException("TenantId must not be empty.");
        }
    }

    private static void RequireId(Guid id, string name)
    {
        if (id == Guid.Empty)
        {
            throw new DomainException($"{name} must not be empty.");
        }
    }
}
