// Task 041D, R1/R2/R3: the media-seek budget.
//
//   media seek <= 500ms
//
// This is the only budget whose evidence is a real media element, and getting
// there needed one non-obvious thing. The synthetic preview is fulfilled through
// `page.route`, and a media element that is fulfilled *without* `Range` support
// reports `seekable = [0, 0]`: every seek is a silent no-op that still fires
// `seeked`, and a naive assertion passes while measuring nothing. `fulfillRange`
// in `support/fixtures.ts` answers 206 with a `Content-Range`, and the spec
// asserts `video.seekable` really spans the fixture before timing anything.
//
// The measurement requires two independent facts, not one:
//
//   1. the element fired `seeked` at the requested position, and
//   2. the position the player *renders* matches the request.
//
// A stub that answered `seeked` without the UI moving would fail (2), and a UI
// that updated the label without moving the media would fail (1). That is also
// why the app's own seek path is driven - the player scrubber, the waveform
// scrub, the ruler and the transport buttons - rather than by assigning
// `video.currentTime` from the test: the 120ms interaction debounce is part of
// what a user waits for, and 500ms is the budget it belongs to.
//
// The preview is 60s of synthetic Matroska (100,031 bytes) generated by
// `e2e/perf/fixtures/generate-media.mjs`. It is not a real asset, it is not
// tenant media, and its size is recorded here so the number is readable.

import { existsSync, statSync } from 'node:fs';
import { expect, test } from '@playwright/test';

import { budgetById, formatVerdictLine } from './budgets.js';
import { PREVIEW_MEDIA_FILE, installSyntheticApi, perfProjectId } from './support/fixtures.js';
import { runBudget } from './support/gate.js';
import { installProbes, probeMeasureOpen, probeMeasureSeek, probeText } from './support/probes.js';
import { getPerfSession, hostProfileOneLine, repoFile } from './support/session.js';

const BUDGET = budgetById('media-seek');

/** Seek targets, in ms. Distinct per sample so `seeked` always fires. */
const SEEK_TARGETS: readonly number[] = [8_000, 21_500, 34_000, 12_250, 47_500, 5_000, 29_750, 41_000];

test(`@perf ${BUDGET.title} <= ${BUDGET.limitMs}ms [${BUDGET.fixture}]`, async ({ browser }, testInfo) => {
  const session = await getPerfSession(browser);
  const { page } = session;
  const projectId = perfProjectId(7);
  const synthetic = await installSyntheticApi(page, {
    projectId,
    segmentCount: 1_200,
    overshootPageSize: true,
  });

  try {
    await installProbes(page);

    await probeMeasureOpen(page, {
      path: `/projects/${projectId}/timeline`,
      testId: 'page-project-timeline',
      selector: '[data-testid="timeline-player"] video',
      count: 1,
    });

    // The player must have resolved the synthetic signed descriptor and put a
    // media element on the page, or "media seek" is not being measured at all.
    await expect(page.getByTestId('timeline-media')).toBeVisible();
    await expect(page.getByTestId('timeline-player')).not.toHaveAttribute('data-compact', 'true');

    // Non-vacuity: the element must actually be seekable before any latency is
    // trusted. See the file header for why this is not paranoia.
    const seekable = await page.evaluate(() => {
      const video = document.querySelector<HTMLVideoElement>('[data-testid="timeline-media"]');
      if (video === null) {
        return { spans: 0, ranges: [] as number[][], error: 'no element', src: '' };
      }
      return {
        spans: video.seekable.length,
        ranges: Array.from({ length: video.seekable.length }, (_unused, index) => [
          Math.round(video.seekable.start(index)),
          Math.round(video.seekable.end(index)),
        ]),
        error: video.error === null ? '' : `code ${String(video.error.code)}`,
        src: video.currentSrc,
      };
    });
    expect(
      seekable.spans,
      `the synthetic preview reports no seekable range (src=${seekable.src}, mediaError=${seekable.error}). ` +
        'A media request fulfilled without Range support makes every seek a silent no-op that still fires ' +
        '`seeked`, so a seeked-only assertion would pass while measuring nothing.',
    ).toBeGreaterThan(0);
    // `TimeRanges` are in SECONDS, not the milliseconds the rest of the app
    // speaks. Comparing them against a millisecond figure is how a real 60s
    // seekable range gets reported as "too short".
    expect(
      seekable.ranges[0]?.[1] ?? 0,
      `the seekable range ends at ${String(seekable.ranges[0]?.[1] ?? 0)}s; the fixture is 60s and every ` +
        'seek target is inside it. A short range means the media element cannot reach the positions ' +
        'this budget asks it to.',
    ).toBeGreaterThan(55);

    // Metadata must be loaded, or the player has no duration and every target
    // collapses onto 0.
    const duration = await probeText(page, 'timeline-duration');
    expect(duration, 'the player never reported a media duration').not.toBe('0 ms');

    const previewPath = repoFile(PREVIEW_MEDIA_FILE);
    expect(
      existsSync(previewPath),
      `the synthetic preview fixture is missing at ${previewPath}. Regenerate it with ` +
        '`node e2e/perf/fixtures/generate-media.mjs`.',
    ).toBe(true);
    const previewBytes = statSync(previewPath).size;

    const result = await runBudget({
      testInfo,
      context: session.visual.context,
      budget: BUDGET,
      measure: async (run) => {
        const latencies: number[] = [];
        const evidence: string[] = [];
        for (let index = 0; index < SEEK_TARGETS.length; index += 1) {
          // Vary the driver so the budget is not one control's latency: the
          // player's scrubber, the waveform's scrub, the ruler and the +/-5s
          // transport all reach the same store by different code paths.
          const target = (SEEK_TARGETS[(run * 3 + index) % SEEK_TARGETS.length] ?? 8_000) + run * 250;
          const driver = index % 4;
          if (driver === 0 || driver === 1) {
            const control = driver === 0 ? 'timeline-scrub' : 'timeline-waveform-scrub';
            const measured = await probeMeasureSeek(page, control, target, 'timeline-media', 'timeline-position');
            latencies.push(measured.ms);
            evidence.push(measured.evidence);
            continue;
          }
          // The ruler and the transport button land on a computed position and
          // cannot be asked for a specific one, so they are recorded as evidence
          // and excluded from the budget's samples. Mixing them in would make the
          // number a mixture of a seek and a click.
          if (driver === 2) {
            const before = await probeText(page, 'timeline-position');
            await page.getByTestId('timeline-seek-forward').click();
            await page.waitForFunction(
              (previous: string) =>
                (document.querySelector('[data-testid="timeline-position"]')?.textContent ?? '').trim() !==
                previous,
              before,
              { timeout: 10_000 },
            );
            evidence.push(`transport +5s from "${before}" -> "${await probeText(page, 'timeline-position')}"`);
            continue;
          }
          await page.getByTestId('timeline-ruler').click({ position: { x: 40 + index * 7, y: 4 } });
          await page.waitForFunction(
            () => {
              const value = (document.querySelector('[data-testid="timeline-position"]')?.textContent ?? '').trim();
              return value !== '' && value !== '0 ms';
            },
            undefined,
            { timeout: 10_000 },
          );
          evidence.push(`ruler click at x=${String(40 + index * 7)} -> "${await probeText(page, 'timeline-position')}"`);
        }

        expect(
          latencies.length,
          `run ${String(run + 1)} recorded no seek through the player's own scrubbers (${evidence.join(' | ')}). ` +
            'The ruler and transport paths cannot be asked for a specific position, so at least the ' +
            'scrubber paths must produce measurable samples or this budget is measuring nothing.',
        ).toBeGreaterThan(0);

        // A run's value is its *worst* seek; the verdict is the median of three
        // worsts. Anything else would let a run hide a slow seek behind a fast
        // one, which is the same class of error as judging a budget on its best
        // sample.
        return {
          valueMs: Math.max(...latencies),
          detail: {
            run: run + 1,
            samples: latencies.length,
            worstMs: Math.round(Math.max(...latencies)),
            bestMs: Math.round(Math.min(...latencies)),
            previewBytes,
            host: hostProfileOneLine(),
          },
        };
      },
    });

    expect(
      result.verdict.verdict,
      `${result.verdict.explanation}\n${formatVerdictLine(BUDGET, result.verdict.comparedMs)}\n` +
        `Trace: ${result.trace?.summary ?? 'not captured'}`,
    ).not.toBe('breach');
  } finally {
    await synthetic.close();
  }
});
